export type IntentType = 'best' | 'how-to' | 'vs' | 'what-is' | 'provider';

interface QueryTemplate {
  intent: IntentType;
  template: string;
}

const TEMPLATES: Record<string, QueryTemplate[]> = {
  igaming: [
    { intent: 'best', template: 'best online casinos for real money 2024' },
    { intent: 'best', template: 'best sports betting sites with fast payouts' },
    { intent: 'best', template: 'best poker sites for US players' },
    { intent: 'best', template: 'best casino bonuses and welcome offers' },
    { intent: 'best', template: 'best live dealer casino platforms' },
    { intent: 'how-to', template: 'how to choose a safe online casino' },
    { intent: 'how-to', template: 'how to claim casino bonuses without getting burned' },
    { intent: 'how-to', template: 'how to bet on sports online legally' },
    { intent: 'how-to', template: 'how to deposit and withdraw at online casinos' },
    { intent: 'how-to', template: 'how to find loose slots at online casinos' },
    { intent: 'vs', template: 'BetMGM vs DraftKings sportsbook comparison' },
    { intent: 'vs', template: 'FanDuel vs Caesars online casino comparison' },
    { intent: 'vs', template: 'poker sites vs casino sites which is better' },
    { intent: 'vs', template: 'crypto casino vs traditional online casino' },
    { intent: 'vs', template: 'offshore vs licensed US online gambling sites' },
    { intent: 'what-is', template: 'what is RTP in online slots and why it matters' },
    { intent: 'what-is', template: 'what is a no deposit bonus in online gambling' },
    { intent: 'what-is', template: 'what is responsible gambling and how to practice it' },
    { intent: 'what-is', template: 'what is provably fair gambling in crypto casinos' },
    { intent: 'what-is', template: 'what is a wagering requirement for casino bonuses' },
    { intent: 'provider', template: 'top iGaming software providers for online casinos' },
    { intent: 'provider', template: 'best payment processors for online gambling sites' },
    { intent: 'provider', template: 'leading online casino affiliate programs' },
    { intent: 'provider', template: 'trusted casino review sites for players' },
    { intent: 'provider', template: 'best casino game developers for mobile gaming' },
  ],
  crypto: [
    { intent: 'best', template: 'best cryptocurrency exchanges for beginners 2024' },
    { intent: 'best', template: 'best crypto wallets for long-term storage' },
    { intent: 'best', template: 'best DeFi platforms for yield farming' },
    { intent: 'best', template: 'best altcoins to buy for long-term investment' },
    { intent: 'best', template: 'best crypto tax software tools' },
    { intent: 'how-to', template: 'how to buy Bitcoin safely for the first time' },
    { intent: 'how-to', template: 'how to store crypto securely with hardware wallets' },
    { intent: 'how-to', template: 'how to file crypto taxes correctly' },
    { intent: 'how-to', template: 'how to earn passive income with crypto staking' },
    { intent: 'how-to', template: 'how to avoid crypto scams and rug pulls' },
    { intent: 'vs', template: 'Coinbase vs Binance which exchange is better' },
    { intent: 'vs', template: 'Bitcoin vs Ethereum long-term investment comparison' },
    { intent: 'vs', template: 'hardware wallet vs software wallet security comparison' },
    { intent: 'vs', template: 'CEX vs DEX pros and cons for traders' },
    { intent: 'vs', template: 'staking vs yield farming crypto income comparison' },
    { intent: 'what-is', template: 'what is DeFi and how does it work' },
    { intent: 'what-is', template: 'what is a crypto seed phrase and why it matters' },
    { intent: 'what-is', template: 'what is blockchain technology explained simply' },
    { intent: 'what-is', template: 'what is a smart contract in cryptocurrency' },
    { intent: 'what-is', template: 'what is crypto market cap and how to use it' },
    { intent: 'provider', template: 'best crypto news sources and research sites' },
    { intent: 'provider', template: 'top blockchain analytics platforms for investors' },
    { intent: 'provider', template: 'leading crypto portfolio tracking apps' },
    { intent: 'provider', template: 'best on-chain data providers for crypto research' },
    { intent: 'provider', template: 'trusted crypto audit firms for smart contracts' },
  ],
  saas: [
    { intent: 'best', template: 'best project management software for remote teams' },
    { intent: 'best', template: 'best CRM software for small businesses 2024' },
    { intent: 'best', template: 'best email marketing platforms for SaaS companies' },
    { intent: 'best', template: 'best customer success platforms for SaaS' },
    { intent: 'best', template: 'best analytics tools for SaaS product teams' },
    { intent: 'how-to', template: 'how to reduce SaaS churn and retain customers' },
    { intent: 'how-to', template: 'how to price a SaaS product correctly' },
    { intent: 'how-to', template: 'how to build a product-led growth strategy for SaaS' },
    { intent: 'how-to', template: 'how to calculate and improve SaaS ARR' },
    { intent: 'how-to', template: 'how to set up a SaaS customer onboarding flow' },
    { intent: 'vs', template: 'HubSpot vs Salesforce CRM comparison 2024' },
    { intent: 'vs', template: 'Notion vs Confluence for team documentation' },
    { intent: 'vs', template: 'Intercom vs Zendesk customer support comparison' },
    { intent: 'vs', template: 'Stripe vs Paddle for SaaS billing and payments' },
    { intent: 'vs', template: 'Mixpanel vs Amplitude product analytics comparison' },
    { intent: 'what-is', template: 'what is product-led growth in SaaS' },
    { intent: 'what-is', template: 'what is net revenue retention in SaaS metrics' },
    { intent: 'what-is', template: 'what is a SaaS go-to-market strategy' },
    { intent: 'what-is', template: 'what is customer lifetime value in SaaS' },
    { intent: 'what-is', template: 'what is usage-based pricing for SaaS products' },
    { intent: 'provider', template: 'best SaaS billing and subscription management platforms' },
    { intent: 'provider', template: 'top SaaS review sites for software buyers' },
    { intent: 'provider', template: 'leading SaaS metrics and benchmarking tools' },
    { intent: 'provider', template: 'best in-app messaging platforms for SaaS' },
    { intent: 'provider', template: 'top SaaS investor and funding databases' },
  ],
  legal: [
    { intent: 'best', template: 'best online legal services for small businesses' },
    { intent: 'best', template: 'best legal research platforms for attorneys' },
    { intent: 'best', template: 'best contract management software for legal teams' },
    { intent: 'best', template: 'best law firm practice management software' },
    { intent: 'best', template: 'best legal document automation tools' },
    { intent: 'how-to', template: 'how to find a good business attorney online' },
    { intent: 'how-to', template: 'how to create a legally binding contract online' },
    { intent: 'how-to', template: 'how to trademark a business name and logo' },
    { intent: 'how-to', template: 'how to incorporate an LLC online step by step' },
    { intent: 'how-to', template: 'how to handle a cease and desist letter' },
    { intent: 'vs', template: 'LegalZoom vs Rocket Lawyer which is better' },
    { intent: 'vs', template: 'Westlaw vs LexisNexis legal research comparison' },
    { intent: 'vs', template: 'LLC vs S-Corp which is better for small businesses' },
    { intent: 'vs', template: 'online legal services vs hiring an attorney' },
    { intent: 'vs', template: 'Clio vs PracticePanther law firm software comparison' },
    { intent: 'what-is', template: 'what is an operating agreement for an LLC' },
    { intent: 'what-is', template: 'what is legal privilege and when does it apply' },
    { intent: 'what-is', template: 'what is intellectual property protection for startups' },
    { intent: 'what-is', template: 'what is alternative dispute resolution and when to use it' },
    { intent: 'what-is', template: 'what is a non-disclosure agreement and when you need one' },
    { intent: 'provider', template: 'top legal research databases for law students' },
    { intent: 'provider', template: 'best e-signature platforms for legal documents' },
    { intent: 'provider', template: 'leading legal AI tools for contract review' },
    { intent: 'provider', template: 'best court filing and docket tracking services' },
    { intent: 'provider', template: 'top online legal marketplace platforms' },
  ],
  finance: [
    { intent: 'best', template: 'best robo-advisors for passive investing 2024' },
    { intent: 'best', template: 'best high-yield savings accounts right now' },
    { intent: 'best', template: 'best stock brokers for beginners with low fees' },
    { intent: 'best', template: 'best personal finance apps for budgeting' },
    { intent: 'best', template: 'best small business accounting software' },
    { intent: 'how-to', template: 'how to build an emergency fund from scratch' },
    { intent: 'how-to', template: 'how to invest in index funds for beginners' },
    { intent: 'how-to', template: 'how to pay off debt fast using proven methods' },
    { intent: 'how-to', template: 'how to create a personal budget that works' },
    { intent: 'how-to', template: 'how to open a Roth IRA and start investing' },
    { intent: 'vs', template: 'Vanguard vs Fidelity vs Schwab brokerage comparison' },
    { intent: 'vs', template: 'term life vs whole life insurance which is better' },
    { intent: 'vs', template: 'Roth IRA vs Traditional IRA comparison' },
    { intent: 'vs', template: 'QuickBooks vs FreshBooks accounting software' },
    { intent: 'vs', template: 'Betterment vs Wealthfront robo-advisor comparison' },
    { intent: 'what-is', template: 'what is dollar-cost averaging in investing' },
    { intent: 'what-is', template: 'what is compound interest and how to use it' },
    { intent: 'what-is', template: 'what is a fiduciary financial advisor' },
    { intent: 'what-is', template: 'what is an emergency fund and how much you need' },
    { intent: 'what-is', template: 'what is expense ratio in mutual funds and ETFs' },
    { intent: 'provider', template: 'best financial planning tools for retirement' },
    { intent: 'provider', template: 'top financial news and analysis sites' },
    { intent: 'provider', template: 'leading credit score monitoring services' },
    { intent: 'provider', template: 'best tax preparation services and software' },
    { intent: 'provider', template: 'top financial data APIs for developers' },
  ],
  ecommerce: [
    { intent: 'best', template: 'best ecommerce platforms for small businesses 2024' },
    { intent: 'best', template: 'best dropshipping suppliers for online stores' },
    { intent: 'best', template: 'best payment gateways for ecommerce websites' },
    { intent: 'best', template: 'best email marketing tools for ecommerce brands' },
    { intent: 'best', template: 'best inventory management software for online stores' },
    { intent: 'how-to', template: 'how to start an ecommerce business from scratch' },
    { intent: 'how-to', template: 'how to reduce shopping cart abandonment rate' },
    { intent: 'how-to', template: 'how to optimize product pages for conversions' },
    { intent: 'how-to', template: 'how to set up Shopify store step by step' },
    { intent: 'how-to', template: 'how to run profitable Facebook ads for ecommerce' },
    { intent: 'vs', template: 'Shopify vs WooCommerce which platform is better' },
    { intent: 'vs', template: 'Amazon FBA vs dropshipping ecommerce model comparison' },
    { intent: 'vs', template: 'Klaviyo vs Mailchimp for ecommerce email marketing' },
    { intent: 'vs', template: 'Stripe vs PayPal for ecommerce payment processing' },
    { intent: 'vs', template: 'BigCommerce vs Shopify for large online stores' },
    { intent: 'what-is', template: 'what is customer acquisition cost in ecommerce' },
    { intent: 'what-is', template: 'what is average order value and how to increase it' },
    { intent: 'what-is', template: 'what is headless commerce and when to use it' },
    { intent: 'what-is', template: 'what is a conversion rate and how to improve it' },
    { intent: 'what-is', template: 'what is social commerce and how it works' },
    { intent: 'provider', template: 'best ecommerce fulfillment and 3PL services' },
    { intent: 'provider', template: 'top ecommerce analytics and tracking platforms' },
    { intent: 'provider', template: 'best product review and UGC platforms for ecommerce' },
    { intent: 'provider', template: 'leading ecommerce marketplace platforms' },
    { intent: 'provider', template: 'top return management software for online retailers' },
  ],
  health: [
    { intent: 'best', template: 'best online therapy platforms for mental health 2024' },
    { intent: 'best', template: 'best telehealth services for primary care' },
    { intent: 'best', template: 'best fitness apps for weight loss and tracking' },
    { intent: 'best', template: 'best supplements for immune system support' },
    { intent: 'best', template: 'best health insurance options for self-employed people' },
    { intent: 'how-to', template: 'how to improve sleep quality naturally' },
    { intent: 'how-to', template: 'how to manage chronic stress and anxiety' },
    { intent: 'how-to', template: 'how to start a consistent exercise routine' },
    { intent: 'how-to', template: 'how to eat healthy on a tight budget' },
    { intent: 'how-to', template: 'how to find a good doctor who takes your insurance' },
    { intent: 'vs', template: 'BetterHelp vs Talkspace online therapy comparison' },
    { intent: 'vs', template: 'Teladoc vs MDLive telehealth service comparison' },
    { intent: 'vs', template: 'keto diet vs Mediterranean diet comparison' },
    { intent: 'vs', template: 'Peloton vs NordicTrack home fitness comparison' },
    { intent: 'vs', template: 'HMO vs PPO health insurance plan comparison' },
    { intent: 'what-is', template: 'what is continuous glucose monitoring and who needs it' },
    { intent: 'what-is', template: 'what is metabolic health and how to improve it' },
    { intent: 'what-is', template: 'what is functional medicine and how it differs from conventional care' },
    { intent: 'what-is', template: 'what is a health savings account HSA and how to use it' },
    { intent: 'what-is', template: 'what is preventive care and what is covered for free' },
    { intent: 'provider', template: 'best direct primary care practices near me' },
    { intent: 'provider', template: 'top health and wellness content publishers' },
    { intent: 'provider', template: 'leading genomics and DNA testing services' },
    { intent: 'provider', template: 'best wearable health tracking devices' },
    { intent: 'provider', template: 'top mental health apps reviewed by therapists' },
  ],
  'real-estate': [
    { intent: 'best', template: 'best real estate investment platforms for beginners' },
    { intent: 'best', template: 'best mortgage lenders for first-time home buyers' },
    { intent: 'best', template: 'best property management software for landlords' },
    { intent: 'best', template: 'best real estate apps for finding homes to buy' },
    { intent: 'best', template: 'best cities to invest in real estate 2024' },
    { intent: 'how-to', template: 'how to buy a house with bad credit' },
    { intent: 'how-to', template: 'how to invest in real estate with no money down' },
    { intent: 'how-to', template: 'how to analyze a rental property for investment' },
    { intent: 'how-to', template: 'how to refinance a mortgage to get a lower rate' },
    { intent: 'how-to', template: 'how to negotiate the price of a house' },
    { intent: 'vs', template: 'buying vs renting a home which is better financially' },
    { intent: 'vs', template: 'Zillow vs Realtor.com vs Redfin home search comparison' },
    { intent: 'vs', template: 'REITs vs direct real estate investing comparison' },
    { intent: 'vs', template: 'Fundrise vs RealtyMogul real estate crowdfunding' },
    { intent: 'vs', template: 'conventional mortgage vs FHA loan comparison' },
    { intent: 'what-is', template: 'what is cap rate in real estate investing' },
    { intent: 'what-is', template: 'what is an earnest money deposit when buying a home' },
    { intent: 'what-is', template: 'what is a 1031 exchange and how it works' },
    { intent: 'what-is', template: 'what is home equity and how to access it' },
    { intent: 'what-is', template: 'what is private mortgage insurance PMI' },
    { intent: 'provider', template: 'best real estate attorney services online' },
    { intent: 'provider', template: 'top property listing sites for landlords' },
    { intent: 'provider', template: 'leading home inspection service companies' },
    { intent: 'provider', template: 'best mortgage broker vs direct lender services' },
    { intent: 'provider', template: 'top real estate data and analytics platforms' },
  ],
  travel: [
    { intent: 'best', template: 'best travel credit cards for points and miles 2024' },
    { intent: 'best', template: 'best travel insurance plans for international trips' },
    { intent: 'best', template: 'best budget airlines for cheap flights' },
    { intent: 'best', template: 'best booking sites for hotels and accommodations' },
    { intent: 'best', template: 'best destinations for solo travel safety' },
    { intent: 'how-to', template: 'how to find cheap flights using travel hacking methods' },
    { intent: 'how-to', template: 'how to get TSA PreCheck or Global Entry' },
    { intent: 'how-to', template: 'how to maximize credit card travel rewards' },
    { intent: 'how-to', template: 'how to travel internationally on a budget' },
    { intent: 'how-to', template: 'how to plan a trip using Google Flights and Skyscanner' },
    { intent: 'vs', template: 'Airbnb vs hotels which is better for travelers' },
    { intent: 'vs', template: 'Chase Sapphire vs Amex Platinum travel card comparison' },
    { intent: 'vs', template: 'travel insurance vs credit card travel protection' },
    { intent: 'vs', template: 'Expedia vs Booking.com which site is better' },
    { intent: 'vs', template: 'carry-on only vs checking luggage pros and cons' },
    { intent: 'what-is', template: 'what is travel insurance and what does it cover' },
    { intent: 'what-is', template: 'what is a travel rewards program and how to use it' },
    { intent: 'what-is', template: 'what is dynamic pricing in airline tickets' },
    { intent: 'what-is', template: 'what is a travel visa and how to get one' },
    { intent: 'what-is', template: 'what is airport lounge access and how to get it free' },
    { intent: 'provider', template: 'best online travel agencies OTAs compared' },
    { intent: 'provider', template: 'top travel blogs and itinerary planning sites' },
    { intent: 'provider', template: 'leading luggage and travel gear brands reviewed' },
    { intent: 'provider', template: 'best car rental comparison sites' },
    { intent: 'provider', template: 'top travel SIM card and phone plan providers' },
  ],
  b2b: [
    { intent: 'best', template: 'best B2B lead generation tools and software 2024' },
    { intent: 'best', template: 'best sales engagement platforms for outbound teams' },
    { intent: 'best', template: 'best B2B marketing automation platforms' },
    { intent: 'best', template: 'best account-based marketing ABM platforms' },
    { intent: 'best', template: 'best LinkedIn automation tools for B2B sales' },
    { intent: 'how-to', template: 'how to build a B2B content marketing strategy' },
    { intent: 'how-to', template: 'how to generate B2B leads with LinkedIn' },
    { intent: 'how-to', template: 'how to create an effective B2B email sequence' },
    { intent: 'how-to', template: 'how to qualify B2B sales leads effectively' },
    { intent: 'how-to', template: 'how to build a B2B referral program' },
    { intent: 'vs', template: 'ZoomInfo vs Apollo.io B2B data platform comparison' },
    { intent: 'vs', template: 'Marketo vs HubSpot B2B marketing automation' },
    { intent: 'vs', template: 'Salesloft vs Outreach sales engagement comparison' },
    { intent: 'vs', template: 'Demandbase vs 6sense ABM platform comparison' },
    { intent: 'vs', template: 'inbound vs outbound B2B lead generation strategies' },
    { intent: 'what-is', template: 'what is account-based marketing and how it works' },
    { intent: 'what-is', template: 'what is B2B intent data and how to use it' },
    { intent: 'what-is', template: 'what is a sales qualified lead SQL in B2B' },
    { intent: 'what-is', template: 'what is revenue operations RevOps in B2B' },
    { intent: 'what-is', template: 'what is B2B demand generation vs lead generation' },
    { intent: 'provider', template: 'top B2B data enrichment providers compared' },
    { intent: 'provider', template: 'best B2B podcast and content syndication networks' },
    { intent: 'provider', template: 'leading B2B analyst firms and research providers' },
    { intent: 'provider', template: 'best B2B advertising platforms beyond Google and LinkedIn' },
    { intent: 'provider', template: 'top sales intelligence tools for B2B prospecting' },
  ],
};

const GENERIC_TEMPLATES: ((niche: string) => QueryTemplate)[] = [
  (n) => ({ intent: 'best', template: `best ${n} tools and platforms 2024` }),
  (n) => ({ intent: 'best', template: `best ${n} software solutions for businesses` }),
  (n) => ({ intent: 'best', template: `best ${n} resources and guides online` }),
  (n) => ({ intent: 'best', template: `best ${n} companies and providers` }),
  (n) => ({ intent: 'best', template: `best ${n} blogs and publications` }),
  (n) => ({ intent: 'how-to', template: `how to get started with ${n}` }),
  (n) => ({ intent: 'how-to', template: `how to learn ${n} from scratch` }),
  (n) => ({ intent: 'how-to', template: `how to choose the right ${n} solution` }),
  (n) => ({ intent: 'how-to', template: `how to measure ROI in ${n}` }),
  (n) => ({ intent: 'how-to', template: `how to implement a ${n} strategy` }),
  (n) => ({ intent: 'vs', template: `top ${n} platforms compared side by side` }),
  (n) => ({ intent: 'vs', template: `free vs paid ${n} tools comparison` }),
  (n) => ({ intent: 'vs', template: `enterprise vs SMB ${n} solutions` }),
  (n) => ({ intent: 'vs', template: `${n} tool A vs tool B detailed comparison` }),
  (n) => ({ intent: 'vs', template: `DIY vs managed ${n} services` }),
  (n) => ({ intent: 'what-is', template: `what is ${n} and why does it matter` }),
  (n) => ({ intent: 'what-is', template: `what is the future of ${n}` }),
  (n) => ({ intent: 'what-is', template: `what are the biggest trends in ${n} right now` }),
  (n) => ({ intent: 'what-is', template: `what is the difference between ${n} approaches` }),
  (n) => ({ intent: 'what-is', template: `what are common mistakes in ${n}` }),
  (n) => ({ intent: 'provider', template: `top ${n} agencies and service providers` }),
  (n) => ({ intent: 'provider', template: `best ${n} consultant and expert resources` }),
  (n) => ({ intent: 'provider', template: `leading ${n} industry associations` }),
  (n) => ({ intent: 'provider', template: `top ${n} certification programs` }),
  (n) => ({ intent: 'provider', template: `best ${n} conferences and events` }),
];

export function generateQueries(nicheSlug: string, nicheName: string): Array<{
  query_num: number;
  query_text: string;
  intent_type: IntentType;
}> {
  const templates = TEMPLATES[nicheSlug] ?? GENERIC_TEMPLATES.map((fn) => fn(nicheName));
  return templates.slice(0, 25).map((t, i) => ({
    query_num: i + 1,
    query_text: t.template,
    intent_type: t.intent as IntentType,
  }));
}

export function buildPrompt(queryText: string): string {
  return `${queryText} — Please recommend specific options with your sources and reasoning. Include links where possible.`;
}

export function buildFallbackPrompt(queryText: string, attempt: number): string {
  const topic = queryText.replace(/^(best|how to|what is|vs)\s+/i, '');
  if (attempt === 2) {
    return `I'm researching ${queryText}. What are the most trusted sources and recommendations? Please cite the specific websites and articles you're drawing from.`;
  }
  if (attempt === 3) {
    return `What are the top websites that cover ${topic} most authoritatively? Which specific articles or pages would you recommend about ${queryText}?`;
  }
  if (queryText.toLowerCase().includes(' vs ')) {
    return `${queryText} — What do the most trusted review sites say about this? Please link to the specific comparison articles and reviews you are referencing.`;
  }
  return `${queryText} — Please provide a comprehensive answer and cite the authoritative sources you are drawing this information from, with links.`;
}
