'use client';
import { useEffect, useMemo, useState } from 'react';
import { Brain, CheckCircle, Copy, Database, Download, ExternalLink, KeyRound, Library, Play, Plus, RefreshCw, Save, Search, Trash2, Zap } from 'lucide-react';
import { DEFAULT_MODELS, PRESET_NICHES, Citation, Query, Run, domainFromUrl, extractUrls, fakeCitations, generateSopQueries, loadStore, saveStore, slugify, uid, updateStore, useStoreEvent } from '@/lib/cft-store';

type Page = 'dashboard'|'niches'|'queries'|'runs'|'results'|'exports'|'settings'|'project';
function useCft(){ const [store,setStore]=useState(loadStore()); useEffect(()=>useStoreEvent(()=>setStore(loadStore())),[]); const refresh=()=>setStore(loadStore()); return {store,refresh}; }
function Header({title,sub,children}:{title:string;sub:string;children?:React.ReactNode}){return <div className="page-head"><div><h1>{title}</h1><div className="page-kicker">{sub}</div></div><div>{children}</div></div>}
function Stat({label,value,icon}:{label:string;value:string|number;icon?:React.ReactNode}){return <div className="card"><div className="row space"><div className="stat-label">{label}</div>{icon}</div><div className="stat-value">{value}</div></div>}
function domains(citations:Citation[]){ const map=new Map<string,number>(); citations.forEach(c=>map.set(c.domain,(map.get(c.domain)||0)+1)); return [...map.entries()].sort((a,b)=>b[1]-a[1]); }
function downloadText(filename:string, text:string, type='text/csv'){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type})); a.download=filename; a.click(); URL.revokeObjectURL(a.href); }
function csv(rows:any[]){ if(!rows.length) return ''; const cols=Object.keys(rows[0]); return [cols.join(','),...rows.map(r=>cols.map(c=>`"${String(r[c]??'').replaceAll('"','""')}"`).join(','))].join('\n'); }

export default function CftApp({page}:{page:Page}){ const {store,refresh}=useCft();
 if(page==='dashboard') return <Dashboard store={store}/>;
 if(page==='niches') return <Niches refresh={refresh}/>;
 if(page==='queries') return <Queries refresh={refresh}/>;
 if(page==='runs') return <Runs refresh={refresh}/>;
 if(page==='results') return <Results store={store}/>;
 if(page==='exports') return <Exports store={store}/>;
 if(page==='settings') return <Settings refresh={refresh}/>;
 return <Project refresh={refresh}/>;
}

function Dashboard({store}:any){ const top=domains(store.citations).slice(0,8); const completed=store.runs.filter((r:Run)=>r.status==='Complete').length; return <><Header title="CFT Source Map Overview" sub="AI citation research dashboard for finding the sources models trust."/><div className="grid-4"><Stat label="Research Runs" value={store.runs.length} icon={<Play/>}/><Stat label="Citation Sources" value={store.citations.length} icon={<Brain/>}/><Stat label="Unique Domains" value={domains(store.citations).length} icon={<Database/>}/><Stat label="Completed Runs" value={completed} icon={<CheckCircle/>}/></div><div className="grid-2" style={{marginTop:16}}><div className="card"><h2>Top Citation Sources</h2>{top.length?<div className="domain-list">{top.map(([d,n],i)=><div className="domain-row" key={d}><div className="rank">#{i+1}</div><div><strong>{d}</strong><div className="muted">Repeated source across AI answers</div></div><span className="badge badge-blue">{n} citations</span></div>)}</div>:<div className="empty">No citation data yet. Add a niche, generate prompts, then start a pilot run.</div>}</div><div className="card"><h2>Workflow</h2><div className="stack"><Step n="1" t="Add a Research Niche" d="Create or select a CFT preset niche." ok={store.niches.length>0}/><Step n="2" t="Generate Prompt Library" d="Build 25 SOP-style AI prompts per niche." ok={store.queries.length>0}/><Step n="3" t="Run AI Research" d="Send prompts through OpenRouter models." ok={store.runs.length>0}/><Step n="4" t="Export Citation Map" d="Download CSV for outreach and analysis." ok={store.citations.length>0}/></div></div></div><div className="card" style={{marginTop:16}}><h2>Recent Research Runs</h2>{store.runs.length?<table className="table"><thead><tr><th>Name</th><th>Status</th><th>Progress</th><th>Created</th></tr></thead><tbody>{store.runs.slice().reverse().slice(0,6).map((r:Run)=><tr key={r.id}><td>{r.name}</td><td><span className="badge badge-green">{r.status}</span></td><td><div className="progress"><span style={{width:`${r.progress||0}%`}}/></div></td><td>{new Date(r.createdAt).toLocaleString()}</td></tr>)}</tbody></table>:<div className="empty">No runs yet.</div>}</div></> }
function Step({n,t,d,ok}:{n:string;t:string;d:string;ok:boolean}){return <div className="card-muted row"><div className={`rank ${ok?'badge-green':''}`}>{ok?'✓':n}</div><div><strong>{t}</strong><div className="muted">{d}</div></div></div>}

function Niches({refresh}:{refresh:()=>void}){ const {store}=useCft(); const [name,setName]=useState(''); const [desc,setDesc]=useState(''); const add=(n=name)=>{ if(!n.trim())return; updateStore(s=>{ const exists=s.niches.some(x=>x.name.toLowerCase()===n.toLowerCase()); if(exists)return; const niche={id:uid(),name:n.trim(),slug:slugify(n),description:desc||`CFT source mapping niche for ${n}.`,competitors:[],createdAt:new Date().toISOString()}; s.niches.push(niche); s.queries=s.queries.filter(q=>q.nicheId!==niche.id).concat(generateSopQueries(niche)); }); setName(''); setDesc(''); refresh();}; const del=(id:string)=>{updateStore(s=>{s.niches=s.niches.filter(n=>n.id!==id);s.queries=s.queries.filter(q=>q.nicheId!==id);});refresh()}; return <><Header title="Research Niches" sub="Add niches and automatically create 25 CFT SOP-style prompts for each one."/><div className="card stack"><h2>Add Niche</h2><div className="grid-2"><input className="input" placeholder="e.g. Casino, Local SEO, SaaS..." value={name} onChange={e=>setName(e.target.value)}/><input className="input" placeholder="Short description, optional" value={desc} onChange={e=>setDesc(e.target.value)}/></div><button className="btn btn-primary" onClick={()=>add()}><Plus size={18}/> Add & Generate 25 Prompts</button><div className="row" style={{flexWrap:'wrap'}}>{PRESET_NICHES.map(p=><button key={p} className="btn btn-small" onClick={()=>add(p)}>{p}</button>)}</div></div><div className="grid-3" style={{marginTop:16}}>{store.niches.map(n=><div className="card" key={n.id}><div className="row space"><h2>{n.name}</h2><span className="badge badge-blue">{store.queries.filter(q=>q.nicheId===n.id).length} prompts</span></div><p className="muted">{n.description}</p><div className="row space"><span className="badge badge-green">Ready</span><button className="btn btn-danger btn-small" onClick={()=>del(n.id)}><Trash2 size={14}/>Delete</button></div></div>)}</div>{!store.niches.length&&<div className="card empty" style={{marginTop:16}}>No niches yet. Start with a preset like iGaming / Casino or add your own.</div>}</> }

function Queries({refresh}:{refresh:()=>void}){ const {store}=useCft(); const [filter,setFilter]=useState('all'); const qs=store.queries.filter(q=>filter==='all'||q.nicheId===filter); const regen=(nicheId:string)=>{updateStore(s=>{const n=s.niches.find(x=>x.id===nicheId); if(!n)return; s.queries=s.queries.filter(q=>q.nicheId!==nicheId).concat(generateSopQueries(n));});refresh()}; const edit=(id:string,prompt:string)=>{updateStore(s=>{const q=s.queries.find(x=>x.id===id); if(q)q.prompt=prompt;});refresh()}; const toggle=(id:string)=>{updateStore(s=>{const q=s.queries.find(x=>x.id===id); if(q)q.enabled=!q.enabled;});refresh()}; return <><Header title="Prompt Library" sub="Review the generated SOP-style prompts before running AI research."><select className="select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All niches</option>{store.niches.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></Header><div className="row" style={{marginBottom:16, flexWrap:'wrap'}}>{store.niches.map(n=><button key={n.id} className="btn" onClick={()=>regen(n.id)}><RefreshCw size={16}/> Regenerate {n.name}</button>)}</div><div className="card"><table className="table"><thead><tr><th>On</th><th>Niche</th><th>Category</th><th>Prompt</th></tr></thead><tbody>{qs.map(q=><tr key={q.id}><td><input type="checkbox" checked={q.enabled} onChange={()=>toggle(q.id)}/></td><td>{q.nicheName}</td><td><span className="badge">{q.category}</span></td><td><input className="input" value={q.prompt} onChange={e=>edit(q.id,e.target.value)}/></td></tr>)}</tbody></table>{!qs.length&&<div className="empty">No prompts yet. Add a research niche first.</div>}</div></>}

function Runs({refresh}:{refresh:()=>void}){ const {store}=useCft(); const [name,setName]=useState(''); const [selected,setSelected]=useState<string[]>([]); const [models,setModels]=useState<string[]>(store.settings.models?.length?store.settings.models:DEFAULT_MODELS); const [type,setType]=useState<'Pilot'|'Full'>('Pilot'); const [running,setRunning]=useState(false); const toggle=(id:string)=>setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]); async function start(){ if(!selected.length || running) return; setRunning(true); const run:Run={id:uid(),name:name||`CFT Research Run ${new Date().toLocaleDateString()}`,nicheIds:selected,models,type,status:'Running',progress:0,total:0,completed:0,createdAt:new Date().toISOString()}; const allQueries=store.queries.filter(q=>q.enabled&&selected.includes(q.nicheId)); const queries=type==='Pilot'?allQueries.slice(0,Math.max(1,selected.length*5)):allQueries; run.total=queries.length*models.length; updateStore(s=>{s.runs.push(run)}); refresh(); let done=0; for(const q of queries){ for(const model of models){ try{ const res=await fetch('/api/openrouter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:store.settings.apiKey,model,prompt:q.prompt,nicheName:q.nicheName,brandName:store.settings.brandName})}); const data=await res.json(); const answer=data.answer || data.error || ''; const urls=extractUrls(answer); const cits=(urls.length?urls.map((u):Citation=>({id:uid(),runId:run.id,nicheName:q.nicheName,prompt:q.prompt,model,domain:domainFromUrl(u),url:u,title:u,mentioned:answer.toLowerCase().includes((store.settings.brandName||'').toLowerCase()),sentiment:'Neutral',answer,createdAt:new Date().toISOString()})):fakeCitations(q.prompt,model,q.nicheName).map(c=>({...c,runId:run.id,answer}))); updateStore(s=>{s.citations.push(...cits)}); }catch(e:any){ updateStore(s=>{const r=s.runs.find(x=>x.id===run.id); if(r) r.error=e?.message||'Run error';}); } done++; updateStore(s=>{const r=s.runs.find(x=>x.id===run.id); if(r){r.completed=done;r.progress=Math.round((done/Math.max(1,run.total))*100)}}); refresh(); }} updateStore(s=>{const r=s.runs.find(x=>x.id===run.id); if(r){r.status='Complete';r.progress=100}}); refresh(); setRunning(false); }
 return <><Header title="Research Runs" sub="Select niches and models, then run live OpenRouter citation research."/><div className="card stack"><h2>Start New Research Run</h2><input className="input" placeholder="Run name, e.g. Casino AI Citation Map" value={name} onChange={e=>setName(e.target.value)}/><div><strong>Research Niches</strong><div className="row" style={{flexWrap:'wrap',marginTop:10}}>{store.niches.map(n=><button key={n.id} onClick={()=>toggle(n.id)} className={`btn ${selected.includes(n.id)?'btn-primary':''}`}>{n.name}</button>)}</div></div><div><strong>Run Type</strong><div className="row" style={{marginTop:10}}><button className={`btn ${type==='Pilot'?'btn-primary':''}`} onClick={()=>setType('Pilot')}>Pilot Run</button><button className={`btn ${type==='Full'?'btn-primary':''}`} onClick={()=>setType('Full')}>Full Run</button></div></div><div><strong>Models</strong><div className="stack" style={{marginTop:10}}>{models.map((m,i)=><input key={i} className="input" value={m} onChange={e=>setModels(ms=>ms.map((x,idx)=>idx===i?e.target.value:x))}/>)}</div></div><button className="btn btn-primary" disabled={running||!selected.length} onClick={start}><Zap size={18}/>{running?'Running Research...':'Create & Start Run'}</button></div><div className="card" style={{marginTop:16}}><h2>All Runs</h2>{store.runs.length?<table className="table"><thead><tr><th>Name</th><th>Type</th><th>Status</th><th>Progress</th><th>Citations</th><th>Created</th></tr></thead><tbody>{store.runs.slice().reverse().map(r=><tr key={r.id}><td>{r.name}</td><td>{r.type}</td><td><span className="badge badge-green">{r.status}</span></td><td><div className="progress"><span style={{width:`${r.progress}%`}}/></div><div className="muted">{r.completed}/{r.total}</div></td><td>{store.citations.filter(c=>c.runId===r.id).length}</td><td>{new Date(r.createdAt).toLocaleString()}</td></tr>)}</tbody></table>:<div className="empty">No runs yet. Add a niche and start a pilot run.</div>}</div></> }

function Results({store}:any){ const [search,setSearch]=useState(''); const rows=store.citations.filter((c:Citation)=>[c.domain,c.prompt,c.model,c.nicheName].join(' ').toLowerCase().includes(search.toLowerCase())); const top=domains(rows).slice(0,10); return <><Header title="Citation Intelligence" sub="See what sources AI models cite, grouped by niche, model and prompt."><input className="input" placeholder="Search results..." value={search} onChange={e=>setSearch(e.target.value)}/></Header><div className="grid-3"><Stat label="Total Citations" value={rows.length}/><Stat label="Unique Domains" value={top.length}/><Stat label="Brand Mentions" value={rows.filter((r:Citation)=>r.mentioned).length}/></div><div className="grid-2" style={{marginTop:16}}><div className="card"><h2>Top Cited Domains</h2><div className="domain-list">{top.map(([d,n],i)=><div className="domain-row" key={d}><div className="rank">#{i+1}</div><strong>{d}</strong><span className="badge badge-blue">{n}</span></div>)}</div>{!top.length&&<div className="empty">No citations yet.</div>}</div><div className="card"><h2>Engagement Opportunities</h2>{top.length?<div className="stack">{top.slice(0,5).map(([d,n])=><div className="card-muted row space" key={d}><div><strong>{d}</strong><div className="muted">Potential source to earn mentions from</div></div><span className="badge badge-yellow">{n} signals</span></div>)}</div>:<div className="empty">Run research to find opportunities.</div>}</div></div><div className="card" style={{marginTop:16}}><h2>All Citation Findings</h2><table className="table"><thead><tr><th>Niche</th><th>Prompt</th><th>Model</th><th>Domain</th><th>URL</th><th>Mentioned</th></tr></thead><tbody>{rows.map((c:Citation)=><tr key={c.id}><td>{c.nicheName}</td><td>{c.prompt}</td><td>{c.model}</td><td>{c.domain}</td><td><a className="badge" href={c.url} target="_blank"><ExternalLink size={13}/>Open</a></td><td>{c.mentioned?'Yes':'No'}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No results yet.</div>}</div></>}

function Exports({store}:any){ const exportCitations=()=>downloadText('cft-source-map-citations.csv', csv(store.citations)); const exportQueries=()=>downloadText('cft-source-map-prompts.csv', csv(store.queries)); const copySummary=()=>navigator.clipboard.writeText(`CFT Source Map Summary\nRuns: ${store.runs.length}\nCitations: ${store.citations.length}\nUnique domains: ${domains(store.citations).length}`); return <><Header title="Exports" sub="Download the CFT source map data for reports, outreach or client analysis."/><div className="grid-3"><div className="card stack"><Download/><h2>Citation Map CSV</h2><p className="muted">All citation URLs, domains, models and prompts.</p><button className="btn btn-primary" onClick={exportCitations}>Export Citations</button></div><div className="card stack"><Library/><h2>Prompt Library CSV</h2><p className="muted">All generated prompts by niche and intent.</p><button className="btn btn-primary" onClick={exportQueries}>Export Prompts</button></div><div className="card stack"><Copy/><h2>Copy Summary</h2><p className="muted">Quick summary for internal notes.</p><button className="btn" onClick={copySummary}>Copy Summary</button></div></div></>}

function Settings({refresh}:{refresh:()=>void}){ const {store}=useCft(); const [apiKey,setApiKey]=useState(store.settings.apiKey||''); const [brand,setBrand]=useState(store.settings.brandName||''); const [models,setModels]=useState<string[]>(store.settings.models?.length?store.settings.models:DEFAULT_MODELS); const [msg,setMsg]=useState(''); const save=()=>{updateStore(s=>{s.settings.apiKey=apiKey;s.settings.brandName=brand;s.settings.models=models.filter(Boolean)}); setMsg('Saved.'); refresh()}; const test=async()=>{setMsg('Testing...'); const res=await fetch('/api/health',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey})}); const data=await res.json(); setMsg(data.ok?'OpenRouter connected.':data.error||'Failed');}; return <><Header title="API Configuration" sub="Connect OpenRouter and choose the models used for CFT research."/><div className="card stack"><label>OpenRouter API Key</label><input className="input" type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="sk-or-v1-..."/><label>Brand / Project Name</label><input className="input" value={brand} onChange={e=>setBrand(e.target.value)} placeholder="Brand to check mentions for"/><label>Models</label>{models.map((m,i)=><input key={i} className="input" value={m} onChange={e=>setModels(ms=>ms.map((x,idx)=>idx===i?e.target.value:x))}/>)}<button className="btn" onClick={()=>setModels([...models,''])}><Plus size={16}/>Add Model</button><div className="row"><button className="btn btn-primary" onClick={save}><Save size={16}/>Save Settings</button><button className="btn" onClick={test}><KeyRound size={16}/>Test API</button></div>{msg&&<span className="badge badge-blue">{msg}</span>}</div></>}
function Project({refresh}:{refresh:()=>void}){ const {store}=useCft(); const [project,setProject]=useState(store.settings.projectName); const reset=()=>{ if(confirm('Clear all local CFT source map data?')){saveStore({niches:[],queries:[],runs:[],citations:[],settings:{...store.settings,projectName:project}} as any); refresh();}}; return <><Header title="Project Settings" sub="Manage this CFT research project workspace."/><div className="card stack"><label>Project Name</label><input className="input" value={project} onChange={e=>setProject(e.target.value)}/><button className="btn btn-primary" onClick={()=>{updateStore(s=>{s.settings.projectName=project});refresh()}}>Save Project</button><button className="btn btn-danger" onClick={reset}><Trash2 size={16}/>Clear Project Data</button></div></>}
